### ISSUE TITLE
Add a practical example for php-pam usage in the documentation

### ISSUE THREAD

**Issue by cristian-ciobanu** [amishmm/php-pam#10]
Please update the README document with a practical code example about how to use this module inside an application.
Thank you.

**Comment by amishmm** [comment]
README has API on the top with parameters described just below it.

And it is self explanatory.

```
if (!pam_auth($user, $pass, $error, true, 'php')) {
    //login failed
    return false;
}
return true;
```
Overall above example is just one-line code and not much different from API. So I dont think we need any specific example.

**Comment by cristian-ciobanu** [comment]
OK! thank you.
