### ISSUE TITLE
Take ownership of unmaintained official PAM package?

### ISSUE THREAD

**Issue by mi-hol** [amishmm/php-pam#3]
Hi Amish,
thanks for making the code compatible with PHP 8.
As you invested already the time to improve the code, how do you think about becoming the official maintainer for https://pecl.php.net/package/PAM ?

**Comment by amishmm** [comment]
I tried applying to pecl mailing list but noone has responded yet to application. Lets see

**Comment by mi-hol** [comment]
Did you succeed with the proposed[ PECL account](https://news-web.php.net/php.pecl.dev/17374)?

**Comment by amishmm** [comment]
No, no response after I applied for PECL account.

**Comment by amishmm** [comment]
Ok after another email - they granted me the permission. Closing this issue. Thanks.

**Comment by mi-hol** [comment]
Would it make sense to reopen and close when the module appears in official PECL?
This would give me a trigger for following up on required changes in another project

**Comment by mi-hol** [comment]
Great achievement!
You are listed as maintainer for https://pecl.php.net/package/PAM
