### ISSUE TITLE
Invalid value of xmlns:xsi attribute in package.xml

### ISSUE THREAD

**Issue by mlocati** [amishmm/php-pam#9]
[We have](https://github.com/amishmm/php-pam/blob/v2.2.3/package.xml#L2) this attribute of the root `package` element:

```xml
xmlns:xsi="http://www.w3.org/2001/XMLSchema- instance"
```

This is wrong. The correct value is

```xml
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
```

(please remark that removed empty space between `XMLSchema-` and `instance`).

See https://www.w3.org/TR/2001/REC-xmlschema-1-20010502/structures.xml#Instance_Document_Constructions

**Comment by amishmm** [comment]
Thanks it will be fixed in next release. (Its already committed in master)

I do not think it makes any difference w.r.t the code. I am not an XML expert or PECL package expert. I just copy-pasted from the original unmaintained package.

Let me know if anything else is wrong. Thank you

**Comment by mlocati** [comment]
The problem is that the XML is malformed with that wrong namespace.
When loading it we have this warning:

```
xmlns:xsi: 'http://www.w3.org/2001/XMLSchema- instance' is not a valid URI in Entity
```

See https://3v4l.org/L8750
